# Generated by Django 5.1.4 on 2025-08-18 10:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('complete', '完成'), ('published', '已发布'), ('deleted', '已删除')], default='draft', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('place_type', models.CharField(blank=True, max_length=255)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('guests', models.IntegerField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basic_info_completed', models.BooleanField(default=False)),
                ('location_completed', models.BooleanField(default=False)),
                ('images_completed', models.BooleanField(default=False)),
                ('pricing_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftPropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('file_url', models.URLField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('etag', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='media_upload.draftproperty')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '等待上传'), ('uploading', '上传中'), ('completed', '已完成'), ('partial', '部分完成'), ('failed', '失败'), ('expired', '已过期')], default='pending', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('uploaded_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('draft_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='media_upload.draftproperty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='draftproperty',
            index=models.Index(fields=['user', 'status'], name='media_uploa_user_id_defdc6_idx'),
        ),
        migrations.AddIndex(
            model_name='draftproperty',
            index=models.Index(fields=['updated_at'], name='media_uploa_updated_2a6801_idx'),
        ),
        migrations.AddIndex(
            model_name='draftpropertyimage',
            index=models.Index(fields=['draft_property', 'is_active'], name='media_uploa_draft_p_6f7de3_idx'),
        ),
        migrations.AddIndex(
            model_name='draftpropertyimage',
            index=models.Index(fields=['object_key'], name='media_uploa_object__203e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['user', 'status'], name='media_uploa_user_id_dd7653_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['expires_at'], name='media_uploa_expires_d820d6_idx'),
        ),
    ]
