# Generated by Django 5.1.4 on 2025-08-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_redesign_propertyimage_r2_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('inactive', '已下架')], default='published', max_length=20),
        ),
    ]
