# Generated by Django 5.1.4 on 2025-01-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_country_code_property_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='type',
            new_name='place_type',
        ),
    ]
