# Generated by Django 5.1.4 on 2025-05-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='property_large'),
        ),
    ]
