# Generated by Django 5.1.4 on 2025-05-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_propertyimage_image_large'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image_xlarge',
            field=models.ImageField(blank=True, null=True, upload_to='property_xlarge'),
        ),
    ]
