# Generated by Django 5.1.4 on 2025-08-14 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_reviewtag_propertyreview_reviewtagassignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
