# Generated by Django 5.1.4 on 2025-08-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_property_options'),
    ]

    operations = [
    ]
