# Generated by Django 5.1.4 on 2025-08-30 15:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_add_updated_at_to_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_tags',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), 
                blank=True, 
                default=list, 
                size=None
            ),
        ),
    ]