# Generated by Django 5.1.4 on 2025-01-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='participants',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='sender',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='receiver',
            new_name='sent_to',
        ),
    ]
