# Generated by Django 5.1.4 on 2025-08-04 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='邮箱是否已验证'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='邮箱验证时间', null=True),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='验证令牌', max_length=64, unique=True)),
                ('email', models.EmailField(help_text='待验证邮箱', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('expires_at', models.DateTimeField(help_text='过期时间')),
                ('is_used', models.BooleanField(default=False, help_text='是否已使用')),
                ('used_at', models.DateTimeField(blank=True, help_text='使用时间', null=True)),
                ('verification_type', models.CharField(choices=[('registration', '注册验证'), ('email_change', '邮箱更改'), ('reactivation', '重新激活'), ('password_reset', '密码重置')], default='registration', help_text='验证类型', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='请求IP地址', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='用户代理信息', null=True)),
                ('user', models.ForeignKey(help_text='关联用户', on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '邮箱验证',
                'verbose_name_plural': '邮箱验证',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='useraccount_token_121248_idx'), models.Index(fields=['email', 'is_used'], name='useraccount_email_4200e5_idx'), models.Index(fields=['user', 'verification_type'], name='useraccount_user_id_cebced_idx'), models.Index(fields=['expires_at'], name='useraccount_expires_b275f5_idx')],
            },
        ),
    ]
