# Generated by Django 5.1.4 on 2025-05-08 06:56

import useraccount.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=useraccount.utils.avatar_upload_path),
        ),
    ]
