# Generated by Django 5.1.4 on 2025-08-04 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_user_email_verified_user_email_verified_at_and_more'),
    ]

    operations = [
        
    ]
