export enum ErrorType {
    AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
    NETWORK_ERROR = 'NETWORK_ERROR',
    SERVER_ERROR = 'SERVER_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    NOT_FOUND = 'NOT_FOUND',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    RATE_LIMITED = 'RATE_LIMITED', 
    CANCELED = 'CANCELED',
    DEFAULT = 'DEFAULT',
  }