services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: /usr/src/airnest_backend/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/airnest_backend
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=airnest

volumes:
  postgres_data:
