# Generated by Django 5.1.4 on 2025-05-08 11:49

import property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_timezone_alter_reservation_check_in_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='property_medium'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='property_thumbnails'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=property.models.property_image_path),
        ),
    ]
