# Generated by Django 5.1.4 on 2025-05-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_propertyimage_image_xlarge'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image_main_jpg',
            field=models.ImageField(blank=True, null=True, upload_to='property_main_jpg'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_original',
            field=models.ImageField(blank=True, null=True, upload_to='property_original'),
        ),
    ]
